import { describe, it, expect } from "vitest";
import { createDefaultTemplate } from "./template.js";

describe("createDefaultTemplate", () => {
  it("should create a default template with empty dependencies", () => {
    const template = createDefaultTemplate({});
    
    expect(template).toHaveProperty("index.js");
    expect(template).toHaveProperty("README.md");
    expect(template).toHaveProperty("package.json");
    
    expect(template["index.js"]).toBe("");
  });

  it("should include all dependencies in package.json", () => {
    const deps = {
      "test-package": "https://pkg.khulnasoft.com/test@1.0.0",
      "another-package": "https://pkg.khulnasoft.com/another@2.0.0",
    };
    
    const template = createDefaultTemplate(deps);
    const packageJson = JSON.parse(template["package.json"]);
    
    expect(packageJson.dependencies).toEqual(deps);
    expect(packageJson.name).toBe("default");
    expect(packageJson.version).toBe("1.0.0");
    expect(packageJson.main).toBe("index.js");
  });

  it("should generate README with install commands for each dependency", () => {
    const deps = {
      "pkg-a": "https://pkg.khulnasoft.com/org/repo/pkg-a@abc123",
      "pkg-b": "https://pkg.khulnasoft.com/org/repo/pkg-b@def456",
    };
    
    const template = createDefaultTemplate(deps);
    const readme = template["README.md"];
    
    expect(readme).toContain("npm i https://pkg.khulnasoft.com/org/repo/pkg-a@abc123");
    expect(readme).toContain("npm i https://pkg.khulnasoft.com/org/repo/pkg-b@def456");
  });

  it("should include template description in README", () => {
    const template = createDefaultTemplate({});
    const readme = template["README.md"];
    
    expect(readme).toContain("Default Template");
    expect(readme).toContain("pkg.khulnasoft.com");
    expect(readme).toContain("Interactive Demos");
    expect(readme).toContain("Enhanced Testing");
  });

  it("should handle single dependency correctly", () => {
    const deps = {
      "single-pkg": "https://pkg.khulnasoft.com/test@1.0.0",
    };
    
    const template = createDefaultTemplate(deps);
    const readme = template["README.md"];
    
    expect(readme).toContain("npm i https://pkg.khulnasoft.com/test@1.0.0");
    
    const packageJson = JSON.parse(template["package.json"]);
    expect(Object.keys(packageJson.dependencies)).toHaveLength(1);
  });

  it("should create valid JSON in package.json", () => {
    const deps = {
      "test": "https://test.url",
    };
    
    const template = createDefaultTemplate(deps);
    
    expect(() => JSON.parse(template["package.json"])).not.toThrow();
  });

  it("should include usage instructions in README", () => {
    const template = createDefaultTemplate({});
    const readme = template["README.md"];
    
    expect(readme).toContain("npx pkg-khulnasoft publish");
    expect(readme).toContain("--template");
  });

  it("should set correct package.json metadata", () => {
    const template = createDefaultTemplate({});
    const packageJson = JSON.parse(template["package.json"]);
    
    expect(packageJson.description).toBe("generated by pkg.khulnasoft.com");
    expect(packageJson.author).toBe("pkg.khulnasoft.com");
    expect(packageJson.license).toBe("ISC");
    expect(packageJson.keywords).toEqual([]);
  });

  it("should handle dependencies with special characters in URLs", () => {
    const deps = {
      "@scoped/package": "https://pkg.khulnasoft.com/@scoped/package@1.0.0",
      "pkg-with-dash": "https://pkg.khulnasoft.com/pkg-with-dash@1.0.0",
    };
    
    const template = createDefaultTemplate(deps);
    const packageJson = JSON.parse(template["package.json"]);
    
    expect(packageJson.dependencies["@scoped/package"]).toBe(
      "https://pkg.khulnasoft.com/@scoped/package@1.0.0"
    );
    expect(packageJson.dependencies["pkg-with-dash"]).toBe(
      "https://pkg.khulnasoft.com/pkg-with-dash@1.0.0"
    );
  });

  it("should handle multiple dependencies with varying URL formats", () => {
    const deps = {
      "pkg1": "https://pkg.khulnasoft.com/owner/repo/pkg1@short",
      "pkg2": "https://pkg.khulnasoft.com/pkg2@1234567",
      "@scope/pkg3": "https://pkg.khulnasoft.com/owner/repo/@scope/pkg3@ref",
    };
    
    const template = createDefaultTemplate(deps);
    const readme = template["README.md"];
    
    Object.entries(deps).forEach(([pkg, url]) => {
      expect(readme).toContain(`npm i ${url}`);
    });
  });

  it("should properly format README markdown code blocks", () => {
    const deps = {
      "test-pkg": "https://pkg.khulnasoft.com/test@1.0.0",
    };
    
    const template = createDefaultTemplate(deps);
    const readme = template["README.md"];
    
    expect(readme).toContain("```sh");
    expect(readme).toContain("```");
    expect(readme.match(/```sh/g)?.length).toBeGreaterThan(0);
  });

  it("should create template with no dependencies", () => {
    const template = createDefaultTemplate({});
    const packageJson = JSON.parse(template["package.json"]);
    
    expect(packageJson.dependencies).toEqual({});
  });

  it("should handle large number of dependencies", () => {
    const deps: Record<string, string> = {};
    for (let i = 0; i < 50; i++) {
      deps[`pkg-${i}`] = `https://pkg.khulnasoft.com/pkg-${i}@v${i}`;
    }
    
    const template = createDefaultTemplate(deps);
    const packageJson = JSON.parse(template["package.json"]);
    
    expect(Object.keys(packageJson.dependencies)).toHaveLength(50);
  });
});